import os
import cv2
import torch 
import numpy as np

from time import time
from datetime import datetime
from zoneinfo import ZoneInfo

from ultralytics import YOLO
import supervision as sv

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

from dotenv import load_dotenv
load_dotenv()

# .env file email_settings
from_email = os.getenv("FROM_EMAIL")
password = os.getenv("EMAIL_PASSWORD")
to_email = os.getenv("TO_EMAIL")

if not all([from_email, password, to_email]):
    raise ValueError(
        "Missing FROM_EMAIL, EMAIL_PASSWORD or TO_EMAIL in .env"
    )


# Path to the YOLOv8 model file
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

MODEL_PATH = os.path.join(BASE_DIR, "models", "yolov8n.pt")

if not os.path.exists(MODEL_PATH):
    raise FileNotFoundError(f"Model not found: {MODEL_PATH}")

# Send email function
def send_email(to_email, from_email, image_path, people_detected=1):

    message = MIMEMultipart()

    message['From'] = from_email
    message['To'] = to_email
    message['Subject'] = "Security Alert"
    
    alert_time = datetime.now(
    ZoneInfo("Asia/Kolkata")).strftime("%d-%m-%Y %I:%M:%S %p IST")
    
    body = f"""
    Security Alert

    Detected Persons: {people_detected}

    Timestamp: {alert_time}

    An image has been attached.

    Generated by Intelligent Surveillance System.
    """

    message.attach(MIMEText(body, 'plain'))

    try:
        with open(image_path, "rb") as attachment:

            part = MIMEBase("application", "octet-stream")
            part.set_payload(attachment.read())

            encoders.encode_base64(part)

            part.add_header("Content-Disposition", f"attachment; filename={os.path.basename(image_path)}")

            message.attach(part)

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(from_email, password)
        server.sendmail(from_email, to_email, message.as_string())

        print("Alert email sent successfully")

        server.quit()

    except Exception as e:
        print("Email Error:", e)


class ObjectDetection:

    def __init__(self, capture_index):
        self.capture_index = capture_index
        
        if torch.backends.mps.is_available():
            self.device = "mps"
        elif torch.cuda.is_available():
            self.device = "cuda"
        else:
            self.device = "cpu"
        print("Using Device:", self.device)
        
        self.last_alert_time = 0
        self.alert_cooldown = 30 # seconds for image saving and email alert cooldown

        self.recording = False
        self.video_writer = None
        self.record_start_time = 0
        self.record_duration = 30 # seconds for recording after detection

        self.video_dir = os.path.join(BASE_DIR, "videos")
        os.makedirs(self.video_dir, exist_ok=True)

        self.model = self.load_model()
        self.CLASS_NAMES_DICT = self.model.model.names
        self.box_annotator = sv.BoxAnnotator(color=sv.Color.WHITE,thickness=3)

    def load_model(self):
        model = YOLO(MODEL_PATH)
        model.to(self.device)
        model.fuse()
        return model

    def predict(self, frame):
        results = self.model(frame, verbose=False, conf=0.5)
        return results

    def plot_bboxes(self, results, frame):
        xyxys = []
        confidence = []
        class_ids = []

        # Extract detection for person class
        if len(results) > 0:
            # Use first result object from Ultralytics (batch size 1)
            res = results[0]
            boxes = res.boxes
            cls_arr = boxes.cls.cpu().numpy().astype(int)
            xyxy_arr = boxes.xyxy.cpu().numpy()
            conf_arr = boxes.conf.cpu().numpy()

            person_indices = np.where(cls_arr == 0)[0]
            for i in person_indices:
                xyxys.append(xyxy_arr[i])
                confidence.append(conf_arr[i])
                class_ids.append(int(cls_arr[i]))

            # Visualization with supervision
            detections = sv.Detections.from_ultralytics(res)
            frame = self.box_annotator.annotate(scene=frame, detections=detections)

        return frame, class_ids

    def __call__(self):
        cap = cv2.VideoCapture(self.capture_index)
        assert cap.isOpened(), f"Unable to open camera index {self.capture_index}"
        cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

        frame_count = 0
        self.capture_dir = os.path.join(BASE_DIR, "captures")
        os.makedirs(self.capture_dir, exist_ok=True)

        while True:
            start_time = time()
            ret, frame = cap.read()
            if not ret:
                print("Failed to read frame from capture.")
                break

            results = self.predict(frame)
            frame, class_ids = self.plot_bboxes(results, frame)
            
            if len(class_ids) > 0:
                print(f"Person detected: {len(class_ids)}")

            current_time = time()

            if len(class_ids) > 0:

                if not self.recording:

                    video_time = datetime.now(ZoneInfo("Asia/Kolkata")).strftime("%Y%m%d_%H%M%S")

                    video_path = os.path.join(self.video_dir, f"intrusion_{video_time}.mp4")

                    fourcc = cv2.VideoWriter_fourcc(*'mp4v')

                    self.video_writer = cv2.VideoWriter(video_path, fourcc, 30, (frame.shape[1], frame.shape[0]))

                    self.record_start_time = current_time
                    self.recording = True

                    print("Recording Started")

                if current_time - self.last_alert_time > self.alert_cooldown:

                    image_path = os.path.join(
                        self.capture_dir,
                        f"person_detected_{datetime.now(ZoneInfo('Asia/Kolkata')).strftime('%Y%m%d_%H%M%S')}.jpg"
                    )

                    cv2.imwrite(image_path, frame)

                    print("Image Saved:", image_path)

                    send_email(to_email, from_email, image_path, len(class_ids))

                    self.last_alert_time = current_time

            end_time = time()
            dt = max(end_time - start_time, 1e-6)
            fps = 1.0 / dt
            
            cv2.putText(frame, f'FPS:{int(fps)}', (20, 70), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (0, 255, 0), 2)
            cv2.putText(frame, f"Persons: {len(class_ids)}", (20, 120),cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 0), 2)

            timestamp = datetime.now(ZoneInfo("Asia/Kolkata")).strftime("%d-%m-%Y %I:%M:%S %p IST")
            cv2.putText(frame,timestamp,(20, frame.shape[0] - 20), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)
            
            if self.recording:
                cv2.putText(frame, "REC", (frame.shape[1] - 120, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255),3)
                
            cv2.imshow('YOLOv8 Detection', frame)
            
            if self.recording:

                self.video_writer.write(frame)
                elapsed = time() - self.record_start_time

                if elapsed >= 30:

                    self.video_writer.release()
                    self.video_writer = None
                    self.recording = False

                    print("Recording Saved")
                        

            frame_count += 1
            if cv2.waitKey(5) & 0xFF == 27:
                break

        cap.release()

        if self.video_writer is not None:
            self.video_writer.release()

        cv2.destroyAllWindows()


detector = ObjectDetection(capture_index=0)  
detector()

        